/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AcceptRouteImport } from './routes/accept'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppAdminUsersRouteImport } from './routes/_app.admin.users'
import { Route as AppPSlugIndexRouteImport } from './routes/_app.p.$slug.index'
import { Route as AppPSlugSettingsRouteImport } from './routes/_app.p.$slug.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptRoute = AcceptRouteImport.update({
  id: '/accept',
  path: '/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppPSlugIndexRoute = AppPSlugIndexRouteImport.update({
  id: '/p/$slug/',
  path: '/p/$slug/',
  getParentRoute: () => AppRoute,
} as any)
const AppPSlugSettingsRoute = AppPSlugSettingsRouteImport.update({
  id: '/p/$slug/settings',
  path: '/p/$slug/settings',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept': typeof AcceptRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/profile': typeof AppProfileRoute
  '/projects': typeof AppProjectsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/p/$slug/settings': typeof AppPSlugSettingsRoute
  '/p/$slug/': typeof AppPSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept': typeof AcceptRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/profile': typeof AppProfileRoute
  '/projects': typeof AppProjectsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/p/$slug/settings': typeof AppPSlugSettingsRoute
  '/p/$slug': typeof AppPSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/accept': typeof AcceptRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/p/$slug/settings': typeof AppPSlugSettingsRoute
  '/_app/p/$slug/': typeof AppPSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept'
    | '/login'
    | '/setup'
    | '/profile'
    | '/projects'
    | '/admin/users'
    | '/p/$slug/settings'
    | '/p/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept'
    | '/login'
    | '/setup'
    | '/profile'
    | '/projects'
    | '/admin/users'
    | '/p/$slug/settings'
    | '/p/$slug'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/accept'
    | '/login'
    | '/setup'
    | '/_app/profile'
    | '/_app/projects'
    | '/_app/admin/users'
    | '/_app/p/$slug/settings'
    | '/_app/p/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AcceptRoute: typeof AcceptRoute
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept': {
      id: '/accept'
      path: '/accept'
      fullPath: '/accept'
      preLoaderRoute: typeof AcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/p/$slug/': {
      id: '/_app/p/$slug/'
      path: '/p/$slug'
      fullPath: '/p/$slug/'
      preLoaderRoute: typeof AppPSlugIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/p/$slug/settings': {
      id: '/_app/p/$slug/settings'
      path: '/p/$slug/settings'
      fullPath: '/p/$slug/settings'
      preLoaderRoute: typeof AppPSlugSettingsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppProfileRoute: typeof AppProfileRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppPSlugSettingsRoute: typeof AppPSlugSettingsRoute
  AppPSlugIndexRoute: typeof AppPSlugIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProfileRoute: AppProfileRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppPSlugSettingsRoute: AppPSlugSettingsRoute,
  AppPSlugIndexRoute: AppPSlugIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AcceptRoute: AcceptRoute,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
